name: Deploy Frontend to EC2

on:
  workflow_dispatch:

env:
  ECR_REPOSITORY: frontend-app
  IMAGE_TAG: ${{ github.sha }}
  ECR_REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Use .env.production
        run: cp frontend/.env.production frontend/.env

      - name: Build and push Docker image
        run: |
          IMAGE="${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/frontend-app:${{ github.sha }}"
          echo "Building and pushing image: $IMAGE"
          docker build -t $IMAGE .
          docker push $IMAGE

      - name: SSH into EC2 and deploy container
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.FRONTEND_EC2_HOST }}
          username: ${{ secrets.FRONTEND_EC2_USER }}
          key: ${{ secrets.FRONTEND_EC2_KEY }}
          script: |
            IMAGE="${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/frontend-app:${{ github.sha }}"
            echo "Running container from image: $IMAGE"
            docker pull $IMAGE
            docker stop frontend || true
            docker rm frontend || true
            docker run -d -p 80:80 --name frontend $IMAGE